config/routes.rb
Foolbits::Application.routes.draw do

    constraints(:host => /^foolbits.com/) do
        get '/(*path)', to: redirect { |params, request|
            p request.url
            URI.parse(request.url).tap { |x| x.host = "www.#{x.host}" }.to_s
        }
    end

    get '/auth/:provider/callback', to: 'sessions#create'
    get 'signout', to: 'sessions#destroy'

    get 'user', to: 'sessions#get'

    get 'setup', to: "crypto#setup"
    get 'vault', to: "crypto#vault"
    post 'keypair', to: "crypto#keypair"
    put 'vault', to: "crypto#set_vault"

    get 'faq', to: "faq#index"

    root 'crypto#index'

end

app/models/user.rb
class User < ActiveRecord::Base

    before_save { self.email = email.downcase if email? }
    before_create :create_remember_token

    def User.new_remember_token
        SecureRandom.urlsafe_base64
    end

    def User.encrypt(token)
        Digest::SHA1.hexdigest(token.to_s)
    end

    private

      def create_remember_token
        self.remember_token = User.encrypt(User.new_remember_token)
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/crypto_controller.rb
class CryptoController < ApplicationController

  def index
  end

  def setup
    render "_setup", layout: false
  end

  def vault
    render "_vault", layout: false
  end

  def set_vault
    p "set_vault"
    p params
    current_user.vault = params["vault"]
    current_user.save!
    render json: { status: "ok" }
  end

  def keypair
    current_user.public_key = params["public_key"]
    current_user.private_key = params["private_key"]

    current_user.save!
    render json: { status: "ok" }
  end

end

app/controllers/faq_controller.rb
class FaqController < ApplicationController

    def index
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth_hash = request.env['omniauth.auth']
    case auth_hash.provider
        when 'facebook'
            user = User.find_by_facebook_id auth_hash.uid
            user = User.new if user.nil?

            info = auth_hash.info
            
            user.first_name = info.first_name if user.first_name.nil?
            user.last_name = info.last_name if user.last_name.nil?
            user.email = info.email if user.email.nil?
            user.picture_url = info.image if user.picture_url.nil?

            user.facebook_id = auth_hash.uid if user.facebook_id.nil?
            user.facebook_access_token = auth_hash.credentials.token if auth_hash.credentials.token != user.facebook_access_token

            user.save! if user.changed?
            sign_in user 
    end
    redirect_to '/'
  end

  def destroy
    sign_out
    redirect_to '/'
  end

  def get
    render json: current_user
  end

  protected

  def auth_hash
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crypto_helper.rb
module CryptoHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

end

app/views/crypto/_setup.html.erb
<div data-id="setup">
    <div class="step1">
        <h1>Write your super-secret passphrase...</h1>
        <p>Some tips: 
            <ul>
                <li>don't use your name, address, birthdate or similar</li>
                <li>passphrases containing special chars such as symbols, punctuation marks and numbers are better!</li>
                <li>don't share with anybody (even with your parents or partner :-) ), don't write anywhere! </li>
                <li>your passphrase won't be stored by us or by your device in any case... so be sure to keep it in mind (or your irremediably lose the content of your vault!)</li>
            </ul>
        </p>

        <div class="form-horizontal">
            <div class="form-group">
                <label class="col-lg-2 control-label">Passphrase</label>
                <div class="col-lg-4">
                    <div class="input-group">
                        <input data-id="passphrase" type="password" class="form-control" placeholder="Type here your super-secret passphrase">
                        <span data-id="passphrase-strength" class="input-group-addon">...</span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div data-id="weak_passphrase_alert" class="alert alert-danger" style="display: none;">
                    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                    <strong><%= t(:weak_passphrase_alert).html_safe %></strong>
                </div>
                <label class="col-lg-2  control-label">retype</label>
                <div class="col-lg-4">
                    <input data-id="retype-passphrase" type="password" class="form-control" placeholder="Retype here to check if they">
                </div>
                <div class="col-lg-2">
                    <button data-id="ok-passphrase" class="btn btn-primary" type="button">Ok, generate my vault!</button>
                </div>
            </div>            
        </div>

    </div>
    <div class="step2" style="display:none;">
        <h1>Creating your vault...</h1>
        <p>Just wait few seconds (depending on your device it could be a little bit longer)!</p>
        <ul>
            <li data-id="step2_keypair" style="visibility: hidden;">creating your keypair</li>
            <li data-id="step2_upload" style="visibility: hidden;">uploading your profile</li>
        </ul>

        <div data-id="step2_done" style="visibility: hidden;">
            <h3>Great, your setup is complete now!</h3>
            <p>Click <a>here</a> to go to your vault</p>
        </div>

    </div>
</div>

<script type="text/javascript">
    $(document).ready( function() { 
        setup("[data-id='setup']");
    });
</script>

app/views/crypto/_vault.html.erb
<div data-id="vault">
    <div data-id="locked" style="display:none;">
        <div class="input-group">
            <span data-id="passphrase-strength" class="input-group-addon"><i class="icon-lock"></i></span>
            <input data-id="passphrase" type="password" class="form-control" placeholder="Type your secret passphrase to unlock your vault">
        </div>

    </div>
    <div data-id="unlocked" style="display:none;">

        <textarea></textarea>
            <ul class="nav nav-pills">
                <li data-id="lock-save"><a><i class="icon-save"></i></a></li>
                <li data-id="lock-edit"><a><i class="icon-pencil"></i></a></li>
                <li data-id="lock-lock"><a><i class="icon-off"></i></a></li>
            </ul>
    </div>

    <div id="pending" class="modal fade" data-id="pending_changes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Pending changes</h4>
                </div>
                <div class="modal-body">
                    <p>There're some changes not saved to your vault. If you don't save them, they will be lost.</p>
                </div>
                <div class="modal-footer">
                    <button data-id="discard" type="button" class="btn btn-default" data-dismiss="modal">Discard</button>
                    <button data-id="save" type="button" class="btn btn-primary" data-dismiss="modal">Save</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready( function() { 
        vault("[data-id='vault']");
    });
</script>

app/views/crypto/index.html.erb
<% if not signed_in? %>

  <div class="jumbotron">
      <h1>Mothball your password text-file</h1>
      <p class="lead">Put your secret codes in a super-secure vault, always available and everywhere accessible</p>
      <p><a class="btn btn-lg btn-primary" href="https://foolbits.herokuapp.com/auth/facebook">Sign up for free!</a></p>
  </div>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <div class="row">
        <div class="col-lg-4">
          <%= image_tag "combination-lock-icon.jpg", class: "img-circle", style: "height: 140px;" %>
          <h2>Secure</h2>
          <p>All your data stored in the vault are encrypted/decrypted directly by your own device such as pc, tablet or phone. No clear texts are kept or transmitted over the Internet</p>
          <p><a class="btn btn-default" href="#encryption">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= image_tag "522px-Tris.svg.png", class: "img-circle", style: "width: 140px; height: 140px;" %>
          <h2>Easy</h2>
          <p>Your Internet browser is all you need. Just access the vault from your own personal computer or from a friend's mobile phone. Your data are finally available on your needs</p>
          <p><a class="btn btn-default" href="#easy">View details »</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= image_tag "cloud.jpg", class: "img-circle", style: "height: 140px;" %>
          <h2>Cloud-based</h2>
          <p>Encrypted data are stored in dedicated server farms. Hence equally accessible from your home or when you're just in front of an ATM. Data are  backed up, protecting from the accidental loss</p>
          <p><a class="btn btn-default" href="#cloud">View details »</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->

      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette" id="encryption">
        <div class="col-md-7">
          <h2 class="featurette-heading">Highest encryption grade <span class="text-muted">Your Bank will envy you!</span></h2>
          <p class="lead">Foolbits protects your data using the state of the art in the encryption software: the symmetric AES (256 bits) and the asymmetric RSA (2136 bits). Still in doubt or willing to contribute? Check out yourself our <a href="https://github.com/lordkada/foolbits" target="_blank">code repo</a> on GitHub or join our <a href="https://groups.google.com/forum/#!forum/foolbits" target="_blank">discussion group</a></p>
        </div>
        <div class="col-md-5">
          <%= image_tag "encryption.jpg", class: "featurette-image img-responsive" %>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette" id="easy">
        <div class="col-md-5">
          <%= image_tag "foolbits-example.png", class: "featurette-image img-responsive", style: "margin-left: 25%;" %>
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">It's a child's game <span class="text-muted">Do a test drive now!</span></h2>
          <p class="lead">Foolbits allows you to write a single text page. No unnecessary complications or things to learn, just you and the vault page: type in or "copy and paste" the text and Foolbits will protect it. It has never been easier</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette" id="cloud">
        <div class="col-md-7">
          <h2 class="featurette-heading">No more excuses <span class="text-muted">Mothball your old text files</span></h2>
          <p class="lead">Probably you never took too seriously the idea to adopt a real solution to protect your codes for your online banking, ATM PINs, Credit Card control codes or whatever. But what happens if your PC is stolen or your mobile phone is lost? Is it safe to write your secret codes somewhere in your harddisk or as a note in your phone? We don't think so... Now you have Foolbits, the final solution to your secret codes protection</p>
        </div>
        <div class="col-md-5">
          <%= image_tag "atm-machine.jpg", class: "featurette-image img-responsive" %>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette" id="free">
        <div class="col-md-5">
          <%= image_tag "oh-yeah-its-free.png", class: "featurette-image img-responsive" %>
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">And last but not least... <span class="text-muted">As it is, it's free. Forever.</span></h2>
          <p class="lead">Your vault and basic core features will always be free. No subscription fees, no dues. This is our promise. This is your win.</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->
<% end %>

app/views/faq/index.html.erb
<h1>Frequently Asked Questions</h1>

<ul class="list-group">

    <li class="list-group-item">
        <h2>Is it safe to use Facebook to signup?</h2>
        <p>Facebook is used to create your profile on Foolbits.com or to access the service (it's an easy replacement for username/password). <strong>Then your vault is encrypted by your passphrase which is the real keystone and it is never stored, transmitted or shared</strong>. Anyway if you're not happy to signup with Facebook, please read below!</p>
    </li>

    <li class="list-group-item">
        <h2>Will you provide other methods to signup the service?</h2>
        <p>Yes, a lot of people asked for it... I hope in the next few weeks to have the time to implement other methods (ie classic email/password signup)</p>
    </li>

    <li class="list-group-item">
        <h2>If I forget my passphrase, is the vault lost?</h2>
        <p>Yes, it is not possible to unlock your vault if you lose your passphrase. So, be sure to keep it in mind!</p>
    </li>

    <li class="list-group-item">
        <h2>Why did you create Foolbits?</h2>
        <p>A couple of days before leaving for the holidays I decided to leave my laptop at home. But I had the problem to bring all my access codes on my tablet (my bank uses a quite complex system of codes). So I came up with the idea of ​​creating Foolbits.</p>
    </li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />

    <title><%= content_for?(:title) ? yield(:title) : "Foolbits, your digital vault." %></title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag "jquery-2.0.3.min.js" %>

    <%= javascript_include_tag "forge/jsbn" %>
    <%= javascript_include_tag "forge/aes.js"%>
    <%= javascript_include_tag "forge/asn1.js"%>
    <%= javascript_include_tag "forge/oids.js"%>
    <%= javascript_include_tag "forge/pkcs1.js"%>
    <%= javascript_include_tag "forge/sha1.js"%>
    <%= javascript_include_tag "forge/rsa.js"%>
    <%= javascript_include_tag "forge/util.js"%>
    <%= javascript_include_tag "forge/pki.js"%>
    <%= javascript_include_tag "forge/prng.js"%>
    <%= javascript_include_tag "forge/random.js"%>
    <%= javascript_include_tag "forge/pbkdf2.js"%>
    <%= javascript_include_tag "forge/hmac.js"%>
    <%= javascript_include_tag "forge/pem.js"%>
    <%= javascript_include_tag "crypto" %>
    <%= javascript_include_tag "crypto_utilities" %>
    <%= javascript_include_tag "setup" %>
    <%= javascript_include_tag "vault" %>
    <%= javascript_include_tag "zxcvbn-async" %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= stylesheet_link_tag href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" %>
    <%= javascript_include_tag src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js" %>
    <%= stylesheet_link_tag href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css" %>

    <style id="holderjs-style" type="text/css">.holderjs-fluid {font-size:16px;font-weight:bold;text-align:center;font-family:sans-serif;margin:0}</style>

  </head>
  <body style="">

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=617674131586410";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <div class="navbar-wrapper">
      <div class="navbar navbar-inverse navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <% if signed_in? %>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <% end %>
            <a data-id="home" class="navbar-brand">Foolbits</a>
            <!--<img class="navbar-brand" src="/assets/foolbits_only.png">-->
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="/faq">FAQ</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if signed_in? %>
                <li><img class="user" src="<%=current_user.picture_url%>"></li>
                <li><%=link_to t(:logout), signout_url %></li>
              <% else %>
                <li><a href="https://foolbits.herokuapp.com/auth/facebook">Login</a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container main">

      <%= bootstrap_flash %>
      <div data-id="drop_content">
        <%= yield %>
      </div>

    </div>

    <div style="text-align: center;">
      <a href="https://twitter.com/foolbits" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow @foolbits</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

      <div class="fb-like" data-href="http://facebook.com/foolbits" data-width="450" data-layout="button_count" data-show-faces="false" data-send="true" style="margin-left: 20px;vertical-align: top;"></div>

      <iframe width="85" height="20" src="http://ghbtns.com/github-btn.html?user=lordkada&repo=foolbits&type=watch&count=true" frameborder="0" scrolling="0" allowtransparency="true" style="margin-left: 20px;"></iframe>

    </div>

    <%= javascript_include_tag "application" %>

    <script type="text/javascript">
      setTimeout(function () { window.scrollTo(0, 0);}, 1000);

      $(document).ready(function() {
        $("[data-id='home']").click(function() {
          window.location.href = "/";
        });
      });

    </script>

    <script type="text/javascript">
      window.csrf_token = $("[name='csrf-token']").attr("content")
    </script>

  </body>
</html>